package CSharp3.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.AbstractCellProvider;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;

public class InterfacePropertyDeclaration_Editor extends DefaultNodeEditor {

  /* package */AbstractCellProvider myHidesInheritedMember_Editor_Component5936_0;
  /* package */AbstractCellProvider myAttributed_Editor_Component5936_0;

  public EditorCell createEditorCell(EditorContext context, SNode node) {
    return this.createCollection_5936_0(context, node);
  }

  public EditorCell createCollection_5936_0(EditorContext context, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(context, node);
    setupBasic_Collection_5936_0(editorCell, node, context);
    editorCell.setGridLayout(false);
    editorCell.setUsesBraces(false);
    editorCell.setCanBeFolded(false);
    editorCell.addEditorCell(this.createComponent_5936_1(context, node));
    editorCell.addEditorCell(this.createComponent_5936_0(context, node));
    return editorCell;
  }

  public EditorCell createComponent_5936_0(EditorContext context, SNode node) {
    if (this.myHidesInheritedMember_Editor_Component5936_0 == null) {
      this.myHidesInheritedMember_Editor_Component5936_0 = new HidesInheritedMember_Editor_Component(node);
    }
    EditorCell editorCell = this.myHidesInheritedMember_Editor_Component5936_0.createEditorCell(context);
    setupBasic_Component_5936_0(editorCell, node, context);
    return editorCell;
  }

  public EditorCell createComponent_5936_1(EditorContext context, SNode node) {
    if (this.myAttributed_Editor_Component5936_0 == null) {
      this.myAttributed_Editor_Component5936_0 = new Attributed_Editor_Component(node);
    }
    EditorCell editorCell = this.myAttributed_Editor_Component5936_0.createEditorCell(context);
    setupBasic_Component_5936_1(editorCell, node, context);
    return editorCell;
  }


  private static void setupBasic_Collection_5936_0(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setCellId("Collection_5936_0");
  }

  private static void setupBasic_Component_5936_0(EditorCell editorCell, SNode node, EditorContext context) {
  }

  private static void setupBasic_Component_5936_1(EditorCell editorCell, SNode node, EditorContext context) {
  }

}
