package CSharp3.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class CompilationUnit_Behavior {

  public static void init(SNode thisNode) {
    SPropertyOperations.set(SLinkOperations.getTarget(thisNode, "namespace", true), "isRootNamespace", "" + true);
  }

}
