package CSharp3.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class InterfaceDeclaration_Behavior {

  public static void init(SNode thisNode) {
    ITypeDeclaration_Behavior.call_setAppropriateVisibility_5734555027415889229(thisNode);
  }

}
