package CSharp3.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.AbstractCellProvider;
import jetbrains.mps.nodeEditor.cellProviders.AbstractCellListHandler;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Horizontal;
import jetbrains.mps.nodeEditor.cells.EditorCell_Label;
import jetbrains.mps.lang.editor.cellProviders.RefNodeListHandler;
import jetbrains.mps.smodel.action.NodeFactoryManager;
import jetbrains.mps.nodeEditor.CellActionType;
import jetbrains.mps.nodeEditor.cellActions.CellAction_DeleteNode;
import jetbrains.mps.nodeEditor.cellMenu.DefaultReferenceSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

public class Attributed_Editor_Component extends AbstractCellProvider {

  /* package */AbstractCellListHandler myListHandler_4210_0;

  public Attributed_Editor_Component(SNode node) {
    super(node);
  }

  public EditorCell createEditorCell(EditorContext context) {
    return this.createEditorCell(context, this.getSNode());
  }

  public EditorCell createEditorCell(EditorContext context, SNode node) {
    return this.createCollection_4210_0(context, node);
  }

  public EditorCell createCollection_4210_0(EditorContext context, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(context, node);
    setupBasic_Collection_4210_0(editorCell, node, context);
    editorCell.setGridLayout(false);
    editorCell.setUsesBraces(false);
    editorCell.setCanBeFolded(false);
    editorCell.addEditorCell(this.createRefNodeList_4210_0(context, node));
    return editorCell;
  }

  public EditorCell createRefNodeList_4210_0(EditorContext context, SNode node) {
    if (this.myListHandler_4210_0 == null) {
      this.myListHandler_4210_0 = new Attributed_Editor_Component.attributesListHandler_4210_0(node, "attributes", context);
    }
    EditorCell_Collection editorCell = this.myListHandler_4210_0.createCells(context, new CellLayout_Horizontal(), false);
    setupBasic_RefNodeList_4210_0(editorCell, node, context);
    editorCell.setGridLayout(false);
    editorCell.setUsesBraces(false);
    editorCell.setCanBeFolded(false);
    editorCell.setRole(this.myListHandler_4210_0.getElementRole());
    return editorCell;
  }


  private static void setupBasic_RefNodeList_4210_0(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setCellId("refNodeList_attributes");
  }

  private static void setupBasic_Collection_4210_0(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setCellId("Collection_4210_0");
  }

  private static void setupLabel_RefNodeList_4210_0(EditorCell_Label editorCell, SNode node, EditorContext context) {
  }

  public static class attributesListHandler_4210_0 extends RefNodeListHandler {

    public attributesListHandler_4210_0(SNode ownerNode, String childRole, EditorContext context) {
      super(ownerNode, childRole, context, false);
    }

    public SNode createNodeToInsert(EditorContext context) {
      SNode listOwner = super.getOwner();
      return NodeFactoryManager.createNode(listOwner, context, super.getElementRole());
    }

    public EditorCell createNodeCell(EditorContext context, SNode elementNode) {
      EditorCell elementCell = super.createNodeCell(context, elementNode);
      this.installElementCellActions(this.getOwner(), elementNode, elementCell, context);
      return elementCell;
    }

    public EditorCell createEmptyCell(EditorContext context) {
      EditorCell emptyCell = null;
      emptyCell = this.createEmptyCell_internal(context, this.getOwner());
      this.installElementCellActions(super.getOwner(), null, emptyCell, context);
      return emptyCell;
    }

    public EditorCell createEmptyCell_internal(EditorContext context, SNode node) {
      return this.createConstant_4210_0(context, node, "");
    }

    public void installElementCellActions(SNode listOwner, SNode elementNode, EditorCell elementCell, EditorContext context) {
      if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET) == null) {
        elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET, AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET);
        SNode substituteInfoNode = listOwner;
        if (elementNode != null) {
          substituteInfoNode = elementNode;
          elementCell.setAction(CellActionType.DELETE, new CellAction_DeleteNode(elementNode));
        }
        if (elementCell.getSubstituteInfo() == null || elementCell.getSubstituteInfo() instanceof DefaultReferenceSubstituteInfo) {
          elementCell.setSubstituteInfo(new DefaultChildSubstituteInfo(listOwner, elementNode, super.getLinkDeclaration(), context));
        }
      }
    }

    public EditorCell createSeparatorCell(EditorContext context) {
      return super.createSeparatorCell(context);
    }

    public EditorCell createConstant_4210_0(EditorContext context, SNode node, String text) {
      EditorCell_Constant editorCell = new EditorCell_Constant(context, node, text);
      setupBasic_Constant_4210_0(editorCell, node, context);
      setupLabel_Constant_4210_0(editorCell, node, context);
      editorCell.setDefaultText("<<attributes>>");
      return editorCell;
    }


    private static void setupBasic_Constant_4210_0(EditorCell editorCell, SNode node, EditorContext context) {
      editorCell.setCellId("Constant_4210_0");
    }

    private static void setupLabel_Constant_4210_0(EditorCell_Label editorCell, SNode node, EditorContext context) {
    }

}

}
