package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;
import java.util.Iterator;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class AttributeTarget_PropertySupport extends PropertySupport {

  public boolean canSetValue(String value) {
    if (value == null) {
      return true;
    }
    Iterator<AttributeTarget> constants = ListSequence.fromList(AttributeTarget.getConstants()).iterator();
    while (constants.hasNext()) {
      AttributeTarget constant = constants.next();
      if (value.equals(constant.getName())) {
        return true;
      }
    }
    return false;
  }

  public String toInternalValue(String value) {
    if (value == null) {
      return null;
    }
    Iterator<AttributeTarget> constants = ListSequence.fromList(AttributeTarget.getConstants()).iterator();
    while (constants.hasNext()) {
      AttributeTarget constant = constants.next();
      if (value.equals(constant.getName())) {
        return constant.getValueAsString();
      }
    }
    return null;
  }

  public String fromInternalValue(String value) {
    AttributeTarget constant = AttributeTarget.parseValue(value);
    if (constant != null) {
      return constant.getName();
    }
    return "";
  }

}
