package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ExternAliasDirective extends BaseConcept {
  public static final String concept = "CSharp3.structure.ExternAliasDirective";
  public static final String IDENTIFIER = "identifier";

  public ExternAliasDirective(SNode node) {
    super(node);
  }

  public String getIdentifier() {
    return this.getProperty(ExternAliasDirective.IDENTIFIER);
  }

  public void setIdentifier(String value) {
    this.setProperty(ExternAliasDirective.IDENTIFIER, value);
  }


  public static ExternAliasDirective newInstance(SModel sm, boolean init) {
    return (ExternAliasDirective)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.ExternAliasDirective", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ExternAliasDirective newInstance(SModel sm) {
    return ExternAliasDirective.newInstance(sm, false);
  }

}
