package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;
import java.util.Iterator;
import java.util.List;

public interface IInterfaceImplementor extends INodeAdapter {
  public static final String concept = "CSharp3.structure.IInterfaceImplementor";
  public static final String INTERFACE_BASES = "interfaceBases";

  public int getInterfaceBasesesCount();

  public Iterator<InterfaceReference> interfaceBaseses();

  public List<InterfaceReference> getInterfaceBaseses();

  public void addInterfaceBases(InterfaceReference node);

  public void insertInterfaceBases(InterfaceReference prev, InterfaceReference node);

}
