package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Int16Type extends IntegralType {
  public static final String concept = "CSharp3.structure.Int16Type";

  public Int16Type(SNode node) {
    super(node);
  }

  public static Int16Type newInstance(SModel sm, boolean init) {
    return (Int16Type)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.Int16Type", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Int16Type newInstance(SModel sm) {
    return Int16Type.newInstance(sm, false);
  }

}
