package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Int64Type extends IntegralType {
  public static final String concept = "CSharp3.structure.Int64Type";

  public Int64Type(SNode node) {
    super(node);
  }

  public static Int64Type newInstance(SModel sm, boolean init) {
    return (Int64Type)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.Int64Type", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Int64Type newInstance(SModel sm) {
    return Int64Type.newInstance(sm, false);
  }

}
