package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class InterfacePropertyDeclaration extends BaseConcept implements IAttributed, IInterfaceMember {
  public static final String concept = "CSharp3.structure.InterfacePropertyDeclaration";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String HIDES_INHERITED_MEMBER = "hidesInheritedMember";
  public static final String GETTER = "getter";
  public static final String SETTER = "setter";
  public static final String ATTRIBUTES = "attributes";

  public InterfacePropertyDeclaration(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(InterfacePropertyDeclaration.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(InterfacePropertyDeclaration.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(InterfacePropertyDeclaration.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(InterfacePropertyDeclaration.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(InterfacePropertyDeclaration.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(InterfacePropertyDeclaration.VIRTUAL_PACKAGE, value);
  }

  public boolean getHidesInheritedMember() {
    return this.getBooleanProperty(InterfacePropertyDeclaration.HIDES_INHERITED_MEMBER);
  }

  public void setHidesInheritedMember(boolean value) {
    this.setBooleanProperty(InterfacePropertyDeclaration.HIDES_INHERITED_MEMBER, value);
  }

  public InterfacePropertyGetter getGetter() {
    return (InterfacePropertyGetter)this.getChild(InterfacePropertyGetter.class, InterfacePropertyDeclaration.GETTER);
  }

  public void setGetter(InterfacePropertyGetter node) {
    super.setChild(InterfacePropertyDeclaration.GETTER, node);
  }

  public InterfacePropertySetter getSetter() {
    return (InterfacePropertySetter)this.getChild(InterfacePropertySetter.class, InterfacePropertyDeclaration.SETTER);
  }

  public void setSetter(InterfacePropertySetter node) {
    super.setChild(InterfacePropertyDeclaration.SETTER, node);
  }

  public int getAttributesesCount() {
    return this.getChildCount(InterfacePropertyDeclaration.ATTRIBUTES);
  }

  public Iterator<Attribute> attributeses() {
    return this.children(Attribute.class, InterfacePropertyDeclaration.ATTRIBUTES);
  }

  public List<Attribute> getAttributeses() {
    return this.getChildren(Attribute.class, InterfacePropertyDeclaration.ATTRIBUTES);
  }

  public void addAttributes(Attribute node) {
    this.addChild(InterfacePropertyDeclaration.ATTRIBUTES, node);
  }

  public void insertAttributes(Attribute prev, Attribute node) {
    this.insertChild(prev, InterfacePropertyDeclaration.ATTRIBUTES, node);
  }


  public static InterfacePropertyDeclaration newInstance(SModel sm, boolean init) {
    return (InterfacePropertyDeclaration)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.InterfacePropertyDeclaration", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static InterfacePropertyDeclaration newInstance(SModel sm) {
    return InterfacePropertyDeclaration.newInstance(sm, false);
  }

}
