package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class InternalTypeVisibility extends TypeVisibility {
  public static final String concept = "CSharp3.structure.InternalTypeVisibility";

  public InternalTypeVisibility(SNode node) {
    super(node);
  }

  public static InternalTypeVisibility newInstance(SModel sm, boolean init) {
    return (InternalTypeVisibility)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.InternalTypeVisibility", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static InternalTypeVisibility newInstance(SModel sm) {
    return InternalTypeVisibility.newInstance(sm, false);
  }

}
