package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class InterfaceMethodDeclaration extends BaseConcept implements IAttributed, IInterfaceMember {
  public static final String concept = "CSharp3.structure.InterfaceMethodDeclaration";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String HIDES_INHERITED_MEMBER = "hidesInheritedMember";
  public static final String ATTRIBUTES = "attributes";

  public InterfaceMethodDeclaration(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(InterfaceMethodDeclaration.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(InterfaceMethodDeclaration.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(InterfaceMethodDeclaration.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(InterfaceMethodDeclaration.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(InterfaceMethodDeclaration.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(InterfaceMethodDeclaration.VIRTUAL_PACKAGE, value);
  }

  public boolean getHidesInheritedMember() {
    return this.getBooleanProperty(InterfaceMethodDeclaration.HIDES_INHERITED_MEMBER);
  }

  public void setHidesInheritedMember(boolean value) {
    this.setBooleanProperty(InterfaceMethodDeclaration.HIDES_INHERITED_MEMBER, value);
  }

  public int getAttributesesCount() {
    return this.getChildCount(InterfaceMethodDeclaration.ATTRIBUTES);
  }

  public Iterator<Attribute> attributeses() {
    return this.children(Attribute.class, InterfaceMethodDeclaration.ATTRIBUTES);
  }

  public List<Attribute> getAttributeses() {
    return this.getChildren(Attribute.class, InterfaceMethodDeclaration.ATTRIBUTES);
  }

  public void addAttributes(Attribute node) {
    this.addChild(InterfaceMethodDeclaration.ATTRIBUTES, node);
  }

  public void insertAttributes(Attribute prev, Attribute node) {
    this.insertChild(prev, InterfaceMethodDeclaration.ATTRIBUTES, node);
  }


  public static InterfaceMethodDeclaration newInstance(SModel sm, boolean init) {
    return (InterfaceMethodDeclaration)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.InterfaceMethodDeclaration", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static InterfaceMethodDeclaration newInstance(SModel sm) {
    return InterfaceMethodDeclaration.newInstance(sm, false);
  }

}
