package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class InterfacePropertySetter extends BaseConcept implements IAttributed {
  public static final String concept = "CSharp3.structure.InterfacePropertySetter";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String ATTRIBUTES = "attributes";

  public InterfacePropertySetter(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(InterfacePropertySetter.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(InterfacePropertySetter.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(InterfacePropertySetter.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(InterfacePropertySetter.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(InterfacePropertySetter.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(InterfacePropertySetter.VIRTUAL_PACKAGE, value);
  }

  public int getAttributesesCount() {
    return this.getChildCount(InterfacePropertySetter.ATTRIBUTES);
  }

  public Iterator<Attribute> attributeses() {
    return this.children(Attribute.class, InterfacePropertySetter.ATTRIBUTES);
  }

  public List<Attribute> getAttributeses() {
    return this.getChildren(Attribute.class, InterfacePropertySetter.ATTRIBUTES);
  }

  public void addAttributes(Attribute node) {
    this.addChild(InterfacePropertySetter.ATTRIBUTES, node);
  }

  public void insertAttributes(Attribute prev, Attribute node) {
    this.insertChild(prev, InterfacePropertySetter.ATTRIBUTES, node);
  }


  public static InterfacePropertySetter newInstance(SModel sm, boolean init) {
    return (InterfacePropertySetter)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.InterfacePropertySetter", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static InterfacePropertySetter newInstance(SModel sm) {
    return InterfacePropertySetter.newInstance(sm, false);
  }

}
