package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class InterfacePropertyGetter extends BaseConcept implements IAttributed {
  public static final String concept = "CSharp3.structure.InterfacePropertyGetter";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String ATTRIBUTES = "attributes";

  public InterfacePropertyGetter(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(InterfacePropertyGetter.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(InterfacePropertyGetter.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(InterfacePropertyGetter.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(InterfacePropertyGetter.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(InterfacePropertyGetter.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(InterfacePropertyGetter.VIRTUAL_PACKAGE, value);
  }

  public int getAttributesesCount() {
    return this.getChildCount(InterfacePropertyGetter.ATTRIBUTES);
  }

  public Iterator<Attribute> attributeses() {
    return this.children(Attribute.class, InterfacePropertyGetter.ATTRIBUTES);
  }

  public List<Attribute> getAttributeses() {
    return this.getChildren(Attribute.class, InterfacePropertyGetter.ATTRIBUTES);
  }

  public void addAttributes(Attribute node) {
    this.addChild(InterfacePropertyGetter.ATTRIBUTES, node);
  }

  public void insertAttributes(Attribute prev, Attribute node) {
    this.insertChild(prev, InterfacePropertyGetter.ATTRIBUTES, node);
  }


  public static InterfacePropertyGetter newInstance(SModel sm, boolean init) {
    return (InterfacePropertyGetter)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.InterfacePropertyGetter", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static InterfacePropertyGetter newInstance(SModel sm) {
    return InterfacePropertyGetter.newInstance(sm, false);
  }

}
