package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NamespaceAlias extends BaseConcept implements INamedConcept {
  public static final String concept = "CSharp3.structure.NamespaceAlias";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";

  public NamespaceAlias(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(NamespaceAlias.NAME);
  }

  public void setName(String value) {
    this.setProperty(NamespaceAlias.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(NamespaceAlias.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(NamespaceAlias.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(NamespaceAlias.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(NamespaceAlias.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(NamespaceAlias.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(NamespaceAlias.VIRTUAL_PACKAGE, value);
  }


  public static NamespaceAlias newInstance(SModel sm, boolean init) {
    return (NamespaceAlias)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.NamespaceAlias", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NamespaceAlias newInstance(SModel sm) {
    return NamespaceAlias.newInstance(sm, false);
  }

}
