package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NestedTypeVisibility extends TypeVisibility {
  public static final String concept = "CSharp3.structure.NestedTypeVisibility";

  public NestedTypeVisibility(SNode node) {
    super(node);
  }

  public static NestedTypeVisibility newInstance(SModel sm, boolean init) {
    return (NestedTypeVisibility)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.NestedTypeVisibility", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NestedTypeVisibility newInstance(SModel sm) {
    return NestedTypeVisibility.newInstance(sm, false);
  }

}
