package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PrivateTypeVisibility extends NestedTypeVisibility {
  public static final String concept = "CSharp3.structure.PrivateTypeVisibility";

  public PrivateTypeVisibility(SNode node) {
    super(node);
  }

  public static PrivateTypeVisibility newInstance(SModel sm, boolean init) {
    return (PrivateTypeVisibility)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.PrivateTypeVisibility", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PrivateTypeVisibility newInstance(SModel sm) {
    return PrivateTypeVisibility.newInstance(sm, false);
  }

}
