package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ProtectedInternalTypeVisibility extends NestedTypeVisibility {
  public static final String concept = "CSharp3.structure.ProtectedInternalTypeVisibility";

  public ProtectedInternalTypeVisibility(SNode node) {
    super(node);
  }

  public static ProtectedInternalTypeVisibility newInstance(SModel sm, boolean init) {
    return (ProtectedInternalTypeVisibility)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.ProtectedInternalTypeVisibility", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ProtectedInternalTypeVisibility newInstance(SModel sm) {
    return ProtectedInternalTypeVisibility.newInstance(sm, false);
  }

}
