package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TypeVisibility extends BaseConcept {
  public static final String concept = "CSharp3.structure.TypeVisibility";

  public TypeVisibility(SNode node) {
    super(node);
  }

  public static TypeVisibility newInstance(SModel sm, boolean init) {
    return (TypeVisibility)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.TypeVisibility", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TypeVisibility newInstance(SModel sm) {
    return TypeVisibility.newInstance(sm, false);
  }

}
