package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TypeParameter extends BaseConcept implements IAttributed {
  public static final String concept = "CSharp3.structure.TypeParameter";
  public static final String IDENTIFIER = "identifier";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String ATTRIBUTES = "attributes";

  public TypeParameter(SNode node) {
    super(node);
  }

  public String getIdentifier() {
    return this.getProperty(TypeParameter.IDENTIFIER);
  }

  public void setIdentifier(String value) {
    this.setProperty(TypeParameter.IDENTIFIER, value);
  }

  public String getShortDescription() {
    return this.getProperty(TypeParameter.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(TypeParameter.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(TypeParameter.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(TypeParameter.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(TypeParameter.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(TypeParameter.VIRTUAL_PACKAGE, value);
  }

  public int getAttributesesCount() {
    return this.getChildCount(TypeParameter.ATTRIBUTES);
  }

  public Iterator<Attribute> attributeses() {
    return this.children(Attribute.class, TypeParameter.ATTRIBUTES);
  }

  public List<Attribute> getAttributeses() {
    return this.getChildren(Attribute.class, TypeParameter.ATTRIBUTES);
  }

  public void addAttributes(Attribute node) {
    this.addChild(TypeParameter.ATTRIBUTES, node);
  }

  public void insertAttributes(Attribute prev, Attribute node) {
    this.insertChild(prev, TypeParameter.ATTRIBUTES, node);
  }


  public static TypeParameter newInstance(SModel sm, boolean init) {
    return (TypeParameter)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.TypeParameter", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TypeParameter newInstance(SModel sm) {
    return TypeParameter.newInstance(sm, false);
  }

}
