package CSharp3.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;

public class ITypeDeclaration_Behavior {

  public static void init(SNode thisNode) {
  }

  public static void call_setAppropriateVisibility_5734555027415889229(SNode thisNode) {
    if (SNodeOperations.isInstanceOf(SNodeOperations.getParent(thisNode), "CSharp3.structure.ITypeDeclaration")) {
      SLinkOperations.setTarget(thisNode, "visibility", SConceptOperations.createNewNode("CSharp3.structure.PrivateTypeVisibility", null), true);
    } else
    {
      SLinkOperations.setTarget(thisNode, "visibility", SConceptOperations.createNewNode("CSharp3.structure.InternalTypeVisibility", null), true);
    }
  }

}
