package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Attribute extends BaseConcept {
  public static final String concept = "CSharp3.structure.Attribute";
  public static final String TARGET = "target";

  public Attribute(SNode node) {
    super(node);
  }

  public AttributeTarget getTarget() {
    String value = super.getProperty(Attribute.TARGET);
    return AttributeTarget.parseValue(value);
  }

  public void setTarget(AttributeTarget value) {
    super.setProperty(Attribute.TARGET, value.getValueAsString());
  }


  public static Attribute newInstance(SModel sm, boolean init) {
    return (Attribute)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.Attribute", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Attribute newInstance(SModel sm) {
    return Attribute.newInstance(sm, false);
  }

}
