package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ClassDeclaration extends BaseConcept implements ITypeDeclaration, IInterfaceImplementor {
  public static final String concept = "CSharp3.structure.ClassDeclaration";
  public static final String IDENTIFIER = "identifier";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String IS_NESTED_TYPE = "isNestedType";
  public static final String HIDES_INHERITED_MEMBER = "hidesInheritedMember";
  public static final String VISIBILITY = "visibility";
  public static final String MEMBERS = "members";
  public static final String ATTRIBUTES = "attributes";
  public static final String INTERFACE_BASES = "interfaceBases";

  public ClassDeclaration(SNode node) {
    super(node);
  }

  public String getIdentifier() {
    return this.getProperty(ClassDeclaration.IDENTIFIER);
  }

  public void setIdentifier(String value) {
    this.setProperty(ClassDeclaration.IDENTIFIER, value);
  }

  public String getName() {
    return this.getProperty(ClassDeclaration.NAME);
  }

  public void setName(String value) {
    this.setProperty(ClassDeclaration.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(ClassDeclaration.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(ClassDeclaration.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(ClassDeclaration.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(ClassDeclaration.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(ClassDeclaration.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(ClassDeclaration.VIRTUAL_PACKAGE, value);
  }

  public boolean getIsNestedType() {
    return this.getBooleanProperty(ClassDeclaration.IS_NESTED_TYPE);
  }

  public void setIsNestedType(boolean value) {
    this.setBooleanProperty(ClassDeclaration.IS_NESTED_TYPE, value);
  }

  public boolean getHidesInheritedMember() {
    return this.getBooleanProperty(ClassDeclaration.HIDES_INHERITED_MEMBER);
  }

  public void setHidesInheritedMember(boolean value) {
    this.setBooleanProperty(ClassDeclaration.HIDES_INHERITED_MEMBER, value);
  }

  public TypeVisibility getVisibility() {
    return (TypeVisibility)this.getChild(TypeVisibility.class, ClassDeclaration.VISIBILITY);
  }

  public void setVisibility(TypeVisibility node) {
    super.setChild(ClassDeclaration.VISIBILITY, node);
  }

  public int getMembersesCount() {
    return this.getChildCount(ClassDeclaration.MEMBERS);
  }

  public Iterator<IClassMember> memberses() {
    return this.children(IClassMember.class, ClassDeclaration.MEMBERS);
  }

  public List<IClassMember> getMemberses() {
    return this.getChildren(IClassMember.class, ClassDeclaration.MEMBERS);
  }

  public void addMembers(IClassMember node) {
    this.addChild(ClassDeclaration.MEMBERS, node);
  }

  public void insertMembers(IClassMember prev, IClassMember node) {
    this.insertChild(prev, ClassDeclaration.MEMBERS, node);
  }

  public int getAttributesesCount() {
    return this.getChildCount(ClassDeclaration.ATTRIBUTES);
  }

  public Iterator<Attribute> attributeses() {
    return this.children(Attribute.class, ClassDeclaration.ATTRIBUTES);
  }

  public List<Attribute> getAttributeses() {
    return this.getChildren(Attribute.class, ClassDeclaration.ATTRIBUTES);
  }

  public void addAttributes(Attribute node) {
    this.addChild(ClassDeclaration.ATTRIBUTES, node);
  }

  public void insertAttributes(Attribute prev, Attribute node) {
    this.insertChild(prev, ClassDeclaration.ATTRIBUTES, node);
  }

  public int getInterfaceBasesesCount() {
    return this.getChildCount(ClassDeclaration.INTERFACE_BASES);
  }

  public Iterator<InterfaceReference> interfaceBaseses() {
    return this.children(InterfaceReference.class, ClassDeclaration.INTERFACE_BASES);
  }

  public List<InterfaceReference> getInterfaceBaseses() {
    return this.getChildren(InterfaceReference.class, ClassDeclaration.INTERFACE_BASES);
  }

  public void addInterfaceBases(InterfaceReference node) {
    this.addChild(ClassDeclaration.INTERFACE_BASES, node);
  }

  public void insertInterfaceBases(InterfaceReference prev, InterfaceReference node) {
    this.insertChild(prev, ClassDeclaration.INTERFACE_BASES, node);
  }


  public static ClassDeclaration newInstance(SModel sm, boolean init) {
    return (ClassDeclaration)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.ClassDeclaration", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ClassDeclaration newInstance(SModel sm) {
    return ClassDeclaration.newInstance(sm, false);
  }

}
