package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ConstantExpression extends BaseConcept {
  public static final String concept = "CSharp3.structure.ConstantExpression";

  public ConstantExpression(SNode node) {
    super(node);
  }

  public static ConstantExpression newInstance(SModel sm, boolean init) {
    return (ConstantExpression)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.ConstantExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ConstantExpression newInstance(SModel sm) {
    return ConstantExpression.newInstance(sm, false);
  }

}
