package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class CSharp3_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("5522757b-5a0c-4e0c-ad2d-7bbfd910ebc0(CSharp3)");

  public static Language get() {
    return (Language)MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }

}
