package CSharp3.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum GlobalAttributeTarget {
  assembly("assembly", "assembly"),
  module("module", "module");

  private String myName;
  private String myValue;

  GlobalAttributeTarget(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }


  public static List<GlobalAttributeTarget> getConstants() {
    List<GlobalAttributeTarget> list = ListSequence.fromList(new LinkedList<GlobalAttributeTarget>());
    ListSequence.fromList(list).addElement(GlobalAttributeTarget.assembly);
    ListSequence.fromList(list).addElement(GlobalAttributeTarget.module);
    return list;
  }

  public static GlobalAttributeTarget getDefault() {
    return null;
  }

  public static GlobalAttributeTarget parseValue(String value) {
    if (value == null) {
      return GlobalAttributeTarget.getDefault();
    }
    if (value.equals(GlobalAttributeTarget.assembly.getValueAsString())) {
      return GlobalAttributeTarget.assembly;
    }
    if (value.equals(GlobalAttributeTarget.module.getValueAsString())) {
      return GlobalAttributeTarget.module;
    }
    return GlobalAttributeTarget.getDefault();
  }

}
