package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface IClassMember extends INodeAdapter {
  public static final String concept = "CSharp3.structure.IClassMember";
}
