package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class InterfaceEventDeclaration extends BaseConcept implements IAttributed, IInterfaceMember {
  public static final String concept = "CSharp3.structure.InterfaceEventDeclaration";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String HIDES_INHERITED_MEMBER = "hidesInheritedMember";
  public static final String ATTRIBUTES = "attributes";

  public InterfaceEventDeclaration(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(InterfaceEventDeclaration.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(InterfaceEventDeclaration.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(InterfaceEventDeclaration.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(InterfaceEventDeclaration.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(InterfaceEventDeclaration.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(InterfaceEventDeclaration.VIRTUAL_PACKAGE, value);
  }

  public boolean getHidesInheritedMember() {
    return this.getBooleanProperty(InterfaceEventDeclaration.HIDES_INHERITED_MEMBER);
  }

  public void setHidesInheritedMember(boolean value) {
    this.setBooleanProperty(InterfaceEventDeclaration.HIDES_INHERITED_MEMBER, value);
  }

  public int getAttributesesCount() {
    return this.getChildCount(InterfaceEventDeclaration.ATTRIBUTES);
  }

  public Iterator<Attribute> attributeses() {
    return this.children(Attribute.class, InterfaceEventDeclaration.ATTRIBUTES);
  }

  public List<Attribute> getAttributeses() {
    return this.getChildren(Attribute.class, InterfaceEventDeclaration.ATTRIBUTES);
  }

  public void addAttributes(Attribute node) {
    this.addChild(InterfaceEventDeclaration.ATTRIBUTES, node);
  }

  public void insertAttributes(Attribute prev, Attribute node) {
    this.insertChild(prev, InterfaceEventDeclaration.ATTRIBUTES, node);
  }


  public static InterfaceEventDeclaration newInstance(SModel sm, boolean init) {
    return (InterfaceEventDeclaration)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.InterfaceEventDeclaration", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static InterfaceEventDeclaration newInstance(SModel sm) {
    return InterfaceEventDeclaration.newInstance(sm, false);
  }

}
