package CSharp3.structure;

/*Generated by MPS */


public interface IPartialTypeDeclaration extends ITypeDeclaration {
  public static final String concept = "CSharp3.structure.IPartialTypeDeclaration";
  public static final String IS_PARTIAL_TYPE = "isPartialType";

  public boolean getIsPartialType();

  public void setIsPartialType(boolean value);

}
