package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface ITypeMember extends INodeAdapter {
  public static final String concept = "CSharp3.structure.ITypeMember";
  public static final String HIDES_INHERITED_MEMBER = "hidesInheritedMember";

  public boolean getHidesInheritedMember();

  public void setHidesInheritedMember(boolean value);

}
