package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NamespaceDeclaration extends BaseConcept implements INamespaceContainer {
  public static final String concept = "CSharp3.structure.NamespaceDeclaration";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String NAMESPACE = "namespace";
  public static final String EXTERN_ALIAS_DIRECTIVES = "externAliasDirectives";
  public static final String USING_DIRECTIVES = "usingDirectives";
  public static final String NAMESPACE_DECLARATIONS = "namespaceDeclarations";
  public static final String TYPE_DECLARATIONS = "typeDeclarations";

  public NamespaceDeclaration(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(NamespaceDeclaration.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(NamespaceDeclaration.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(NamespaceDeclaration.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(NamespaceDeclaration.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(NamespaceDeclaration.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(NamespaceDeclaration.VIRTUAL_PACKAGE, value);
  }

  public NamespaceNode getNamespace() {
    return (NamespaceNode)this.getChild(NamespaceNode.class, NamespaceDeclaration.NAMESPACE);
  }

  public void setNamespace(NamespaceNode node) {
    super.setChild(NamespaceDeclaration.NAMESPACE, node);
  }

  public int getExternAliasDirectivesesCount() {
    return this.getChildCount(NamespaceDeclaration.EXTERN_ALIAS_DIRECTIVES);
  }

  public Iterator<ExternAliasDirective> externAliasDirectiveses() {
    return this.children(ExternAliasDirective.class, NamespaceDeclaration.EXTERN_ALIAS_DIRECTIVES);
  }

  public List<ExternAliasDirective> getExternAliasDirectiveses() {
    return this.getChildren(ExternAliasDirective.class, NamespaceDeclaration.EXTERN_ALIAS_DIRECTIVES);
  }

  public void addExternAliasDirectives(ExternAliasDirective node) {
    this.addChild(NamespaceDeclaration.EXTERN_ALIAS_DIRECTIVES, node);
  }

  public void insertExternAliasDirectives(ExternAliasDirective prev, ExternAliasDirective node) {
    this.insertChild(prev, NamespaceDeclaration.EXTERN_ALIAS_DIRECTIVES, node);
  }

  public int getUsingDirectivesesCount() {
    return this.getChildCount(NamespaceDeclaration.USING_DIRECTIVES);
  }

  public Iterator<UsingDirective> usingDirectiveses() {
    return this.children(UsingDirective.class, NamespaceDeclaration.USING_DIRECTIVES);
  }

  public List<UsingDirective> getUsingDirectiveses() {
    return this.getChildren(UsingDirective.class, NamespaceDeclaration.USING_DIRECTIVES);
  }

  public void addUsingDirectives(UsingDirective node) {
    this.addChild(NamespaceDeclaration.USING_DIRECTIVES, node);
  }

  public void insertUsingDirectives(UsingDirective prev, UsingDirective node) {
    this.insertChild(prev, NamespaceDeclaration.USING_DIRECTIVES, node);
  }

  public int getNamespaceDeclarationsesCount() {
    return this.getChildCount(NamespaceDeclaration.NAMESPACE_DECLARATIONS);
  }

  public Iterator<NamespaceDeclaration> namespaceDeclarationses() {
    return this.children(NamespaceDeclaration.class, NamespaceDeclaration.NAMESPACE_DECLARATIONS);
  }

  public List<NamespaceDeclaration> getNamespaceDeclarationses() {
    return this.getChildren(NamespaceDeclaration.class, NamespaceDeclaration.NAMESPACE_DECLARATIONS);
  }

  public void addNamespaceDeclarations(NamespaceDeclaration node) {
    this.addChild(NamespaceDeclaration.NAMESPACE_DECLARATIONS, node);
  }

  public void insertNamespaceDeclarations(NamespaceDeclaration prev, NamespaceDeclaration node) {
    this.insertChild(prev, NamespaceDeclaration.NAMESPACE_DECLARATIONS, node);
  }

  public int getTypeDeclarationsesCount() {
    return this.getChildCount(NamespaceDeclaration.TYPE_DECLARATIONS);
  }

  public Iterator<ITypeDeclaration> typeDeclarationses() {
    return this.children(ITypeDeclaration.class, NamespaceDeclaration.TYPE_DECLARATIONS);
  }

  public List<ITypeDeclaration> getTypeDeclarationses() {
    return this.getChildren(ITypeDeclaration.class, NamespaceDeclaration.TYPE_DECLARATIONS);
  }

  public void addTypeDeclarations(ITypeDeclaration node) {
    this.addChild(NamespaceDeclaration.TYPE_DECLARATIONS, node);
  }

  public void insertTypeDeclarations(ITypeDeclaration prev, ITypeDeclaration node) {
    this.insertChild(prev, NamespaceDeclaration.TYPE_DECLARATIONS, node);
  }


  public static NamespaceDeclaration newInstance(SModel sm, boolean init) {
    return (NamespaceDeclaration)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.NamespaceDeclaration", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NamespaceDeclaration newInstance(SModel sm) {
    return NamespaceDeclaration.newInstance(sm, false);
  }

}
