package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NamespaceNode extends BaseConcept {
  public static final String concept = "CSharp3.structure.NamespaceNode";
  public static final String NAME = "name";
  public static final String IS_ROOT_NAMESPACE = "isRootNamespace";

  public NamespaceNode(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(NamespaceNode.NAME);
  }

  public void setName(String value) {
    this.setProperty(NamespaceNode.NAME, value);
  }

  public boolean getIsRootNamespace() {
    return this.getBooleanProperty(NamespaceNode.IS_ROOT_NAMESPACE);
  }

  public void setIsRootNamespace(boolean value) {
    this.setBooleanProperty(NamespaceNode.IS_ROOT_NAMESPACE, value);
  }


  public static NamespaceNode newInstance(SModel sm, boolean init) {
    return (NamespaceNode)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.NamespaceNode", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NamespaceNode newInstance(SModel sm) {
    return NamespaceNode.newInstance(sm, false);
  }

}
