package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ProtectedTypeVisibility extends NestedTypeVisibility {
  public static final String concept = "CSharp3.structure.ProtectedTypeVisibility";

  public ProtectedTypeVisibility(SNode node) {
    super(node);
  }

  public static ProtectedTypeVisibility newInstance(SModel sm, boolean init) {
    return (ProtectedTypeVisibility)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.ProtectedTypeVisibility", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ProtectedTypeVisibility newInstance(SModel sm) {
    return ProtectedTypeVisibility.newInstance(sm, false);
  }

}
