package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PublicTypeVisibility extends TypeVisibility {
  public static final String concept = "CSharp3.structure.PublicTypeVisibility";

  public PublicTypeVisibility(SNode node) {
    super(node);
  }

  public static PublicTypeVisibility newInstance(SModel sm, boolean init) {
    return (PublicTypeVisibility)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.PublicTypeVisibility", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PublicTypeVisibility newInstance(SModel sm) {
    return PublicTypeVisibility.newInstance(sm, false);
  }

}
