package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class QualifiedIdentifier extends BaseConcept {
  public static final String concept = "CSharp3.structure.QualifiedIdentifier";

  public QualifiedIdentifier(SNode node) {
    super(node);
  }

  public static QualifiedIdentifier newInstance(SModel sm, boolean init) {
    return (QualifiedIdentifier)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.QualifiedIdentifier", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static QualifiedIdentifier newInstance(SModel sm) {
    return QualifiedIdentifier.newInstance(sm, false);
  }

}
