package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SimpleType extends Type {
  public static final String concept = "CSharp3.structure.SimpleType";

  public SimpleType(SNode node) {
    super(node);
  }

  public static SimpleType newInstance(SModel sm, boolean init) {
    return (SimpleType)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.SimpleType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SimpleType newInstance(SModel sm) {
    return SimpleType.newInstance(sm, false);
  }

}
