package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class UInt32Type extends IntegralType {
  public static final String concept = "CSharp3.structure.UInt32Type";

  public UInt32Type(SNode node) {
    super(node);
  }

  public static UInt32Type newInstance(SModel sm, boolean init) {
    return (UInt32Type)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.UInt32Type", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static UInt32Type newInstance(SModel sm) {
    return UInt32Type.newInstance(sm, false);
  }

}
