package CSharp3.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class UInt64Type extends IntegralType {
  public static final String concept = "CSharp3.structure.UInt64Type";

  public UInt64Type(SNode node) {
    super(node);
  }

  public static UInt64Type newInstance(SModel sm, boolean init) {
    return (UInt64Type)SModelUtil_new.instantiateConceptDeclaration("CSharp3.structure.UInt64Type", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static UInt64Type newInstance(SModel sm) {
    return UInt64Type.newInstance(sm, false);
  }

}
